#!/usr/bin/env python3
"""Vygeneruje počáteční SQLite databázi (fte_wpl_calculator.db) se schématem
a výchozími referenčními daty (absence, časové dotace pozic).

Referenční data jsou převzata z původní aplikace (inicializace_db.py).
Spusťte znovu pouze pokud chcete resetovat vzorovou databázi do výchozího stavu:
    python3 tools/gen_seed_db.py
"""
import os
import sqlite3

DB_NAME = "fte_wpl_calculator.db"


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    db_path = os.path.join(repo_root, DB_NAME)
    if os.path.exists(db_path):
        os.remove(db_path)

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.execute("""
    CREATE TABLE absence (
        segment TEXT PRIMARY KEY,
        nepritomnost REAL,
        homeoffice REAL
    )
    """)

    cur.execute("""
    CREATE TABLE casove_dotace (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        segment TEXT,
        pozice TEXT,
        service_zone REAL,
        meeting_zone REAL,
        backoffice_zone REAL,
        office_room REAL
    )
    """)

    cur.execute("""
    CREATE TABLE excel_loads (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        load_key TEXT,
        pobocka_id TEXT,
        pobocka_nazev TEXT,
        oteviraci_doba REAL,
        segment TEXT,
        pozice TEXT,
        fte REAL,
        wpl_load REAL,
        created_at TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE calculations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        load_key TEXT,
        calculation_key TEXT,
        segment TEXT,
        total_positions REAL,
        position_list TEXT,
        service_zone REAL,
        meeting_zone REAL,
        backoffice_zone REAL,
        office_room REAL,
        created_at TEXT,
        ref_version_id INTEGER
    )
    """)

    cur.execute("""
    CREATE TABLE ref_data_versions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        created_at TEXT,
        note TEXT,
        absence_json TEXT,
        dotace_json TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE furniture_to_zone (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        segment TEXT,
        furniture TEXT,
        zone TEXT,
        wpl_counter REAL
    )
    """)

    cur.execute("""
    CREATE TABLE layouts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        layout_key TEXT,
        calculation_key TEXT,
        segment TEXT,
        zone TEXT,
        furniture TEXT,
        wpl_assigned REAL,
        calculated_wpl REAL,
        piece_count REAL,
        created_at TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE pobocky (
        id_pobocky TEXT PRIMARY KEY,
        nazev TEXT,
        region TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE calculation_stats (
        calculation_key TEXT PRIMARY KEY,
        load_key TEXT,
        format_typ TEXT,
        celkem_fte REAL,
        celkem_wpl REAL,
        wpl_fte_ratio REAL,
        backoffice_pct REAL,
        meeting_pct REAL,
        created_at TEXT
    )
    """)

    absence_data = [
        ("MMMA", 22.9, 0.7),
        ("EPC", 19.7, 2.5),
        ("HC", 19.8, 5.6),
        ("PROVOZ", 21, 0.5),
        ("EPB", 18.6, 1.5),
        ("SBC", 19.5, 5.5),
        ("RKC", 17.1, 7),
        ("CESTOVNÍ", 0, 0),
        ("OSTATNÍ", 20.1, 2.3),
    ]
    cur.executemany("INSERT INTO absence (segment, nepritomnost, homeoffice) VALUES (?, ?, ?)", absence_data)

    casove_dotace_data = [
        # (segment, pozice, service_zone, meeting_zone, backoffice_zone, office_room)
        # SBC
        ("SBC", "firemní bankéř - medior", None, 20, 80, None),
        ("SBC", "podpora firemních bankéřů", None, 10, 90, None),
        ("SBC", "firemní bankéř - senior", None, 20, 80, None),
        ("SBC", "firemní bankéř - master", None, 20, 80, None),
        ("SBC", "manažer segmentu SB - regionální ředitel", None, None, None, 100),
        ("SBC", "manažer segmentu SB - team leader", None, None, 100, None),
        ("SBC", "spec. pro firemní pojištění - senior", None, 20, 80, None),
        # RKC
        ("RKC", "Ředitel regionálního korporátního centra", None, None, None, 100),
        ("RKC", "korporátní finanční analytik - senior", None, None, 100, None),
        ("RKC", "korporátní finanční analytik - master", None, None, 100, None),
        ("RKC", "spec. korporátní klientely - asistent", None, None, 100, None),
        ("RKC", "korporátní úvěrový specialista - medior", None, None, 100, None),
        ("RKC", "korporátní úvěrový specialista - senior", None, None, 100, None),
        # PROVOZ
        ("PROVOZ", "regionální manažer provozu", None, None, 100, None),
        ("PROVOZ", "manažer provozu pob. sítě - team leader", None, None, 100, None),
        ("PROVOZ", "pobočkový specialista - provoz", None, None, 100, None),
        ("PROVOZ", "spec. provozu pobočkové sítě - medior", None, None, 100, None),
        ("PROVOZ", "spec. provozu pobočkové sítě - senior", None, None, 100, None),
        # OSTATNÍ
        ("OSTATNÍ", "remote firemní bankéř - medior", None, None, 100, None),
        ("OSTATNÍ", "remote MMA bankéř - junior", None, None, 100, None),
        ("OSTATNÍ", "remote MMA bankéř - team leader", None, None, 100, None),
        ("OSTATNÍ", "remote premier bankéř - medior", None, None, 100, None),
        ("OSTATNÍ", "area leader virtuálního centra bydlení", None, None, 100, None),
        ("OSTATNÍ", "hypoteční specialista VCB - medior", None, None, 100, None),
        ("OSTATNÍ", "hypoteční specialista VCB - senior", None, None, 100, None),
        ("OSTATNÍ", "specialista podpory VCB - medior", None, None, 100, None),
        ("OSTATNÍ", "nedefinovaná pozice - 100 pct back office", None, None, 100, None),
        ("OSTATNÍ", "nedefinovaná pozice - 50 pct back office a 50 pct meeting zone", None, 50, 50, None),
        # MMMA
        ("MMMA", "bankéř klientské péče - junior", 95, None, 5, None),
        ("MMMA", "bankéř klientské péče - medior", 95, None, 5, None),
        ("MMMA", "manažer segm. investice - reg. ředitel", None, None, 100, None),
        ("MMMA", "manažer segmentu investice - zástupce", None, None, 100, None),
        ("MMMA", "investiční specialista - medior", None, 60, 40, None),
        ("MMMA", "Retail Lead - area lead", None, None, None, 100),
        ("MMMA", "Retail Lead - regional lead", None, None, None, 100),
        ("MMMA", "Retail Lead - team lead", None, 60, 40, None),
        ("MMMA", "osobní bankéř - junior", 10, 70, 20, None),
        ("MMMA", "osobní bankéř - medior", None, 80, 20, None),
        ("MMMA", "osobní bankéř - senior", None, 80, 20, None),
        ("MMMA", "osobní bankéř - master", None, 80, 20, None),
        ("MMMA", "regionální manažer strategie - medior", None, None, 100, None),
        ("MMMA", "manažer segm. pojištění - reg. ředitel", None, None, 100, None),
        ("MMMA", "pojišťovací specialista - medior", None, 60, 40, None),
        # HC
        ("HC", "hypoteční specialista - medior", None, 40, 60, None),
        ("HC", "hypoteční specialista - senior", None, 40, 60, None),
        ("HC", "manažer segm. hypo - regionální ředitel", None, None, 100, None),
        ("HC", "manažer segmentu hypo - zástupce", None, None, 100, None),
        ("HC", "pobočkový specialista - hypo", None, 40, 60, None),
        # EPC
        ("EPC", "Premier Bus. and Digi Assistant - senior", 100, None, None, None),
        ("EPC", "manaž. segm. Erste Premier - area leader", None, None, None, 100),
        ("EPC", "manaž. segm. Erste Premier - team leader bez portfolia", None, None, 100, None),
        ("EPC", "manaž. segm. Erste Premier - team leader s portfoliem", None, 30, 70, None),
        ("EPC", "premier bankéř - medior", None, 50, 50, None),
        ("EPC", "premier bankéř - master", None, 50, 50, None),
        ("EPC", "premier bankéř - senior", None, 50, 50, None),
        # EPB
        ("EPB", "asistentka EPB - medior", None, None, 100, None),
        ("EPB", "asistentka EPB - master", None, None, 100, None),
        ("EPB", "privátní bankéř - medior", None, 50, 100, None),
        ("EPB", "privátní bankéř - senior", None, 50, 100, None),
        ("EPB", "privátní bankéř - wealth management", None, 50, 100, None),
        ("EPB", "manažer segmentu EPB - regionál. ředitel", None, None, None, 100),
        ("EPB", "manažer segmentu EPB - zástupce", None, None, 100, None),
        # CESTOVNÍ
        ("CESTOVNÍ", "bankéř klientské péče - junior", None, 20, 80, None),
        ("CESTOVNÍ", "bankéř klientské péče - medior", None, 10, 90, None),
        ("CESTOVNÍ", "manažer segm. investice - reg. ředitel", None, 20, 80, None),
        ("CESTOVNÍ", "manažer segmentu investice - zástupce", None, None, 100, None),
        ("CESTOVNÍ", "investiční specialista - medior", None, None, 100, None),
        ("CESTOVNÍ", "Retail Lead - area lead", None, 20, 80, None),
        ("CESTOVNÍ", "Retail Lead - regional lead", None, None, 100, None),
        ("CESTOVNÍ", "Retail Lead - team lead", None, None, 100, None),
        ("CESTOVNÍ", "osobní bankéř - junior", None, None, 100, None),
        ("CESTOVNÍ", "osobní bankéř - medior", None, None, 100, None),
        ("CESTOVNÍ", "osobní bankéř - senior", None, None, 100, None),
        ("CESTOVNÍ", "regionální manažer strategie - medior", None, None, 100, None),
        ("CESTOVNÍ", "manažer segm. pojištění - reg. ředitel", None, None, 100, None),
        ("CESTOVNÍ", "pojišťovací specialista - medior", None, None, 100, None),
        ("CESTOVNÍ", "firemní bankéř - medior", None, None, 100, None),
        ("CESTOVNÍ", "podpora firemních bankéřů", None, None, 100, None),
        ("CESTOVNÍ", "firemní bankéř - senior", None, None, 100, None),
        ("CESTOVNÍ", "manažer segmentu SB - regionální ředitel", None, None, 100, None),
        ("CESTOVNÍ", "manažer segmentu SB - team leader", None, None, 100, None),
        ("CESTOVNÍ", "spec. pro firemní pojištění - senior", None, None, 100, None),
        ("CESTOVNÍ", "hypoteční specialista - medior", None, None, 100, None),
        ("CESTOVNÍ", "hypoteční specialista - senior", None, None, 100, None),
        ("CESTOVNÍ", "manažer segm. hypo - regionální ředitel", None, None, 100, None),
        ("CESTOVNÍ", "manažer segmentu hypo - zástupce", None, None, 100, None),
        ("CESTOVNÍ", "pobočkový specialista - hypo", None, None, 100, None),
        ("CESTOVNÍ", "Premier Bus. and Digi Assistant - senior", None, None, 100, None),
        ("CESTOVNÍ", "manaž. segm. Erste Premier - area leader", None, 50, 50, None),
        ("CESTOVNÍ", "manaž. segm. Erste Premier - team leader bez portfolia", 95, None, 5, None),
        ("CESTOVNÍ", "manaž. segm. Erste Premier - team leader s portfoliem", 95, None, 5, None),
        ("CESTOVNÍ", "premier bankéř - medior", None, None, 100, None),
        ("CESTOVNÍ", "premier bankéř - master", None, None, 100, None),
        ("CESTOVNÍ", "premier bankéř - senior", None, 60, 40, None),
        ("CESTOVNÍ", "asistentka EPB - medior", None, None, 100, None),
        ("CESTOVNÍ", "privátní bankéř - medior", None, None, 100, None),
        ("CESTOVNÍ", "privátní bankéř - senior", None, 60, 40, None),
        ("CESTOVNÍ", "privátní bankéř - wealth management", 10, 70, 20, None),
        ("CESTOVNÍ", "manažer segmentu EPB - regionál. ředitel", None, 80, 20, None),
        ("CESTOVNÍ", "manažer segmentu EPB - zástupce", None, 80, 20, None),
        ("CESTOVNÍ", "regionální manažer provozu", None, None, 100, None),
        ("CESTOVNÍ", "manažer provozu pob. sítě - team leader", None, None, 100, None),
        ("CESTOVNÍ", "pobočkový specialista - provoz", None, 60, 40, None),
        ("CESTOVNÍ", "spec. provozu pobočkové sítě - medior", None, 40, 60, None),
        ("CESTOVNÍ", "spec. provozu pobočkové sítě - senior", None, 40, 60, None),
        ("CESTOVNÍ", "Ředitel regionálního korporátního centra", None, None, 100, None),
        ("CESTOVNÍ", "korporátní finanční analytik - senior", None, None, 100, None),
        ("CESTOVNÍ", "korporátní finanční analytik - master", None, 40, 60, None),
        ("CESTOVNÍ", "spec. korporátní klientely - asistent", None, None, 100, None),
        ("CESTOVNÍ", "korporátní úvěrový specialista - medior", None, None, 100, None),
        ("CESTOVNÍ", "korporátní úvěrový specialista - senior", None, None, 100, None),
        ("CESTOVNÍ", "remote firemní bankéř - medior", None, 30, 70, None),
        ("CESTOVNÍ", "remote premier bankéř - medior", None, 50, 50, None),
        ("CESTOVNÍ", "area leader virtuálního centra bydlení", None, None, 100, None),
        ("CESTOVNÍ", "hypoteční specialista VCB - medior", None, 50, 100, None),
        ("CESTOVNÍ", "hypoteční specialista VCB - senior", None, 50, 100, None),
        ("CESTOVNÍ", "specialista podpory VCB - medior", None, 50, 100, None),
        ("CESTOVNÍ", "nedefinovaná pozice - 100 pct back office", None, None, 100, None),
        ("CESTOVNÍ", "nedefinovaná pozice - 50 pct back office a 50 pct meeting zone", None, None, 100, None),
        ("CESTOVNÍ", "asistentka EPB - master", None, None, 100, None),
        ("CESTOVNÍ", "osobní bankéř - master", None, 80, 20, None),
        ("CESTOVNÍ", "firemní bankéř - master", None, 20, 80, None),
    ]
    cur.executemany("""
        INSERT INTO casove_dotace (segment, pozice, service_zone, meeting_zone, backoffice_zone, office_room)
        VALUES (?, ?, ?, ?, ?, ?)
    """, casove_dotace_data)

    furniture_data = [
        # (segment, furniture, zone, wpl_counter)
        ("OSTATNÍ", "Kancelářské místo", "backoffice_zone", 1),
        ("OSTATNÍ", "Kancelář", "backoffice_zone", 1),
        ("OSTATNÍ", "Flex box", "backoffice_zone", 1),
        ("OSTATNÍ", "Fast track backoffice", "backoffice_zone", 0),
        ("OSTATNÍ", "Jednací místnost", "meeting_zone", 1),

        ("CESTOVNÍ", "Kancelářské místo", "backoffice_zone", 1),
        ("CESTOVNÍ", "Flex box", "backoffice_zone", 1),
        ("CESTOVNÍ", "Fast track backoffice", "backoffice_zone", 0),
        ("CESTOVNÍ", "Kancelář", "office_room", 1),
        ("CESTOVNÍ", "Jednací místnost", "meeting_zone", 1),

        ("CESTOVNÍ POZICE", "Kancelářské místo", "backoffice_zone", 1),
        ("CESTOVNÍ POZICE", "Kancelář", "backoffice_zone", 1),
        ("CESTOVNÍ POZICE", "Flex box", "backoffice_zone", 1),
        ("CESTOVNÍ POZICE", "Fast track backoffice", "backoffice_zone", 0),

        ("EPB", "Kancelářské místo", "backoffice_zone", 1),
        ("EPB", "Flex box", "backoffice_zone", 1),
        ("EPB", "Fast track backoffice", "backoffice_zone", 0),
        ("EPB", "Jednací místnost", "meeting_zone", 1),
        ("EPB", "Kancelář", "office_room", 1),
        ("EPB", "Recepce", "service_zone", 1),
        ("EPB", "Čekací zóna (lounge)", "service_zone", 0),

        ("EPC", "Kancelářské místo", "backoffice_zone", 1),
        ("EPC", "Fast track backoffice", "backoffice_zone", 0),
        ("EPC", "Flex box", "backoffice_zone", 1),
        ("EPC", "Jednací místnost", "meeting_zone", 1),
        ("EPC", "Kancelář", "office_room", 1),
        ("EPC", "Recepce", "service_zone", 1),
        ("EPC", "Čekací zóna (lounge)", "service_zone", 0),

        ("HC", "Kancelářské místo", "backoffice_zone", 1),
        ("HC", "Flex box", "backoffice_zone", 1),
        ("HC", "Fast track backoffice", "backoffice_zone", 0),
        ("HC", "Kancelář", "office_room", 1),

        ("PROVOZ", "Kancelářské místo", "backoffice_zone", 1),
        ("PROVOZ", "Flex box", "backoffice_zone", 1),
        ("PROVOZ", "Fast track backoffice", "backoffice_zone", 0),
        ("PROVOZ", "Kancelář", "office_room", 1),

        ("RKC", "Kancelářské místo", "backoffice_zone", 1),
        ("RKC", "Flex box", "backoffice_zone", 1),
        ("RKC", "Fast track backoffice", "backoffice_zone", 0),
        ("RKC", "Jednací místnost", "meeting_zone", 1),
        ("RKC", "Kancelář", "office_room", 1),
        ("RKC", "Recepce", "service_zone", 1),

        ("SBC", "Kancelářské místo", "backoffice_zone", 1),
        ("SBC", "Flex box", "backoffice_zone", 1),
        ("SBC", "Fast track backoffice", "backoffice_zone", 0),
        ("SBC", "Kancelář", "office_room", 1),

        ("MMMA", "Flex box", "meeting_zone", 1),
        ("MMMA", "Jednací místnost", "meeting_zone", 1),
        ("MMMA", "Semidescreete room", "meeting_zone", 1),
        ("MMMA", "Záliv", "meeting_zone", 1),
        ("MMMA", "Lenka", "meeting_zone", 1),
        ("MMMA", "Kancelář", "office_room", 1),
        ("MMMA", "Theke - nízká", "service_zone", 1),
        ("MMMA", "Theke - vysoká", "service_zone", 1),
        ("MMMA", "Lenka vítací", "service_zone", 1),
        ("MMMA", "Fast track (stolek a židle)", "service_zone", 0),
        ("MMMA", "Čekací zóna (židle)", "service_zone", 0),
        ("MMMA", "Čekací zóna (obývák)", "service_zone", 0),
        ("MMMA", "Lenka", "service_zone", 1),
        ("MMMA", "Martička", "service_zone", 1),
        ("MMMA", "Martička s TT", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu 1/2C (1:1,TT+TT,1WPL)", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu 1/2C (1:1,ARP+TT,1WPL)", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu 1/2C (1:1,ARP+TT+TT,1WPL)", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu C (1:1,TT+TT,1WPL)", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu C (1:1,ARP+TT+TT,1WPL)", "service_zone", 1),
        ("MMMA", "Pokladní ostrov typu C (1:1,ARP+TT+TT,2WPL)", "service_zone", 2),
        ("MMMA", "Pokladna s bezpečnostní nástavbou", "service_zone", 1),
        ("MMMA", "Kancelářské místo", "backoffice_zone", 1),
        ("MMMA", "Fast track backoffice", "backoffice_zone", 0),
        ("MMMA", "Interní zasedací místnost - malá", "backoffice_zone", 0),
        ("MMMA", "Interní zasedací místnost - velká", "backoffice_zone", 1),
        ("MMMA", "Relax zóna", "backoffice_zone", 0),
        ("MMMA", "Flex box", "backoffice_zone", 1),
    ]
    cur.executemany("""
        INSERT INTO furniture_to_zone (segment, furniture, zone, wpl_counter)
        VALUES (?, ?, ?, ?)
    """, furniture_data)

    # (id_pobocky, nazev, region) — seznam poboček pro manuální vytvoření kalkulace
    pobocky_data = [
        ('505', 'Praha 6 - Vítězné nám.', 'Praha'),
        ('134', 'Kladno', 'Severozápadní Čechy'),
        ('338', 'Ostrava - Nová Karolina Park', 'Severní Morava'),
        ('282', 'Pardubice, tř. Míru', 'Východní Čechy'),
        ('486', 'Praha 5 - Štefánikova', 'Praha'),
        ('391', 'Nový Jičín', 'Severní Morava'),
        ('469', 'Praha 4 (Budějovická)', 'Praha'),
        ('540', 'Plzeň - Františkánská', 'Jihozápadní Čechy'),
        ('413', 'Opava', 'Severní Morava'),
        ('123', 'Ústí nad Labem', 'Severozápadní Čechy'),
        ('182', 'Liberec', 'Severozápadní Čechy'),
        ('397', 'Olomouc', 'Severní Morava'),
        ('148', 'Mladá Boleslav', 'Severozápadní Čechy'),
        ('384', 'Havířov - Město', 'Severní Morava'),
        ('372', 'Frýdek-Místek', 'Severní Morava'),
        ('578', 'České Budějovice', 'Jihozápadní Čechy'),
        ('74', 'Hodonín', 'Jižní Morava'),
        ('1', 'Brno (Jánská)', 'Jižní Morava'),
        ('128', 'Beroun', 'Severozápadní Čechy'),
        ('93', 'Kroměříž', 'Jižní Morava'),
        ('84', 'Jihlava', 'Jižní Morava'),
        ('118', 'Znojmo', 'Jižní Morava'),
        ('51', 'Břeclav', 'Jižní Morava'),
        ('368', 'Prostějov', 'Severní Morava'),
        ('144', 'Kralupy nad Vltavou', 'Severozápadní Čechy'),
        ('435', 'Šumperk', 'Severní Morava'),
        ('562', 'Benešov', 'Jihozápadní Čechy'),
        ('218', 'Hradec Králové - ČSA', 'Východní Čechy'),
        ('459', 'Praha 2 (Jugoslávská)', 'Praha'),
        ('511', 'Praha 8 (Sokolovská)', 'Praha'),
        ('228', 'Kolín', 'Východní Čechy'),
        ('174', 'Chomutov', 'Severozápadní Čechy'),
        ('151', 'TRIO Ml. Boleslav', 'Severozápadní Čechy'),
        ('569', 'Příbram', 'Jihozápadní Čechy'),
        ('383', 'Karviná', 'Severní Morava'),
        ('629', 'Tábor', 'Jihozápadní Čechy'),
        ('60', 'Zlín', 'Jižní Morava'),
        ('107', 'Uherské Hradiště', 'Jižní Morava'),
        ('600', 'Jindřichův Hradec', 'Jihozápadní Čechy'),
        ('246', 'Havlíčkův Brod', 'Východní Čechy'),
        ('199', 'Most', 'Severozápadní Čechy'),
        ('272', 'Náchod', 'Východní Čechy'),
        ('656', 'Rokycany', 'Jihozápadní Čechy'),
        ('429', 'Přerov', 'Severní Morava'),
        ('477', 'Praha - OC Chodov', 'Praha'),
        ('636', 'Domažlice', 'Jihozápadní Čechy'),
        ('178', 'Jablonec nad Nisou', 'Severozápadní Čechy'),
        ('100', 'Třebíč', 'Jižní Morava'),
        ('108', 'Uherský Brod', 'Jižní Morava'),
        ('192', 'Litoměřice', 'Severozápadní Čechy'),
        ('253', 'Chrudim', 'Východní Čechy'),
        ('266', 'Jičín', 'Východní Čechy'),
        ('646', 'Karlovy Vary', 'Jihozápadní Čechy'),
        ('114', 'Vyškov', 'Jižní Morava'),
        ('204', 'Teplice', 'Severozápadní Čechy'),
        ('354', 'Kopřivnice', 'Severní Morava'),
        ('653', 'Klatovy', 'Jihozápadní Čechy'),
        ('331', 'Žďár nad Sázavou', 'Východní Čechy'),
        ('3', 'Kounicova', 'Jižní Morava'),
        ('291', 'Rychnov nad Kněžnou', 'Východní Čechy'),
        ('160', 'Česká Lípa', 'Severozápadní Čechy'),
        ('392', 'Valašské Meziříčí', 'Severní Morava'),
        ('541', 'Plzeň - OC Plaza', 'Jihozápadní Čechy'),
        ('167', 'Děčín', 'Severozápadní Čechy'),
        ('307', 'Trutnov', 'Východní Čechy'),
        ('156', 'Rakovník', 'Severozápadní Čechy'),
        ('38', 'Pelhřimov', 'Jižní Morava'),
        ('523', 'Vršovické nám.', 'Praha'),
        ('146', 'Mělník', 'Severozápadní Čechy'),
        ('497', 'Praha 8 - Ládví', 'Praha'),
        ('136', 'Slaný', 'Severozápadní Čechy'),
        ('129', 'Hořovice', 'Severozápadní Čechy'),
        ('366', 'Vsetín', 'Severní Morava'),
        ('512', 'Verneřická', 'Praha'),
        ('348', 'Ostrava - Poruba (U Soudu)', 'Severní Morava'),
        ('191', 'Roudnice nad Labem', 'Severozápadní Čechy'),
        ('377', 'Třinec - Lyžbice', 'Severní Morava'),
        ('519', 'OC Letňany', 'Praha'),
        ('101', 'Moravské Budějovice', 'Jižní Morava'),
        ('612', 'Písek', 'Jihozápadní Čechy'),
        ('474', 'Novodvorská', 'Praha'),
        ('465', 'Vinohradská 112', 'Praha'),
        ('660', 'Sokolov', 'Jihozápadní Čechy'),
        ('386', 'Orlová', 'Severní Morava'),
        ('524', 'Starostrašnická', 'Praha'),
        ('493', 'Strossmayerovo náměstí', 'Praha'),
        ('29', 'Vaňkovka', 'Jižní Morava'),
        ('473', 'Háje', 'Praha'),
        ('471', 'Sofijské náměstí', 'Praha'),
        ('243', 'Nymburk', 'Východní Čechy'),
        ('546', 'Plzeň - Lochotín', 'Jihozápadní Čechy'),
        ('521', 'Praha 9 - Centrum Černý Most', 'Praha'),
        ('393', 'Rožnov pod Radhoštěm', 'Severní Morava'),
        ('75', 'Kyjov', 'Jižní Morava'),
        ('414', 'Hlučín', 'Severní Morava'),
        ('430', 'Hranice', 'Severní Morava'),
        ('362', 'OA Kotva Ostrava-Zábřeh', 'Severní Morava'),
        ('236', 'Čáslav', 'Východní Čechy'),
        ('135', 'Kročehlavy', 'Severozápadní Čechy'),
        ('198', 'Louny', 'Severozápadní Čechy'),
        ('349', 'Ostrava - Dubina', 'Severní Morava'),
        ('344', 'Ostrava - Hrabůvka', 'Severní Morava'),
        ('436', 'Jeseník', 'Severní Morava'),
        ('235', 'Kutná Hora', 'Východní Čechy'),
        ('642', 'Cheb', 'Jihozápadní Čechy'),
        ('52', 'Hustopeče u Brna', 'Jižní Morava'),
        ('43', 'Blansko', 'Jižní Morava'),
        ('387', 'Český Těšín', 'Severní Morava'),
        ('451', 'Praha 1 - Národní', 'Praha'),
        ('571', 'Dobříš', 'Jihozápadní Čechy'),
        ('360', 'Shopping Park Ostrava', 'Severní Morava'),
        ('355', 'Bohumín', 'Severní Morava'),
        ('563', 'Vlašim', 'Jihozápadní Čechy'),
        ('142', 'Brandýs nad Labem', 'Severozápadní Čechy'),
        ('535', 'Říčany', 'Praha'),
        ('145', 'Neratovice', 'Severozápadní Čechy'),
        ('528', 'Topolová', 'Praha'),
        ('241', 'Poděbrady', 'Východní Čechy'),
        ('66', 'Valašské Klobouky', 'Jižní Morava'),
        ('419', 'Krnov', 'Severní Morava'),
        ('11', 'Královo Pole', 'Jižní Morava'),
        ('403', 'Uničov', 'Severní Morava'),
        ('374', 'Jablunkov', 'Severní Morava'),
        ('498', 'Praha 8 - OC Krakov', 'Praha'),
        ('446', 'Václavské náměstí', 'Praha'),
        ('624', 'Strakonice', 'Jihozápadní Čechy'),
        ('22', 'OC Campus Square Brno', 'Jižní Morava'),
        ('219', 'Střelecká', 'Východní Čechy'),
        ('211', 'OC Olympia Teplice-Srbice', 'Severozápadní Čechy'),
        ('299', 'Svitavy', 'Východní Čechy'),
        ('667', 'Stříbro', 'Jihozápadní Čechy'),
        ('64', 'Otrokovice - Atrium', 'Jižní Morava'),
        ('150', 'Mnichovo Hradiště', 'Severozápadní Čechy'),
        ('508', 'Praha 6 - Petřiny', 'Praha'),
        ('27', 'Vinohrady', 'Jižní Morava'),
        ('437', 'Mohelnice', 'Severní Morava'),
        ('438', 'Zábřeh', 'Severní Morava'),
        ('490', 'Luka', 'Praha'),
        ('632', 'Soběslav', 'Jihozápadní Čechy'),
        ('321', 'Ústí nad Orlicí', 'Východní Čechy'),
        ('287', 'OC Globus Pardubice', 'Východní Čechy'),
        ('8', 'Křídlovická', 'Jižní Morava'),
        ('185', 'OC Nisa Liberec', 'Severozápadní Čechy'),
        ('335', 'Velké Meziříčí', 'Východní Čechy'),
        ('376', 'Frýdlant nad Ostravicí', 'Severní Morava'),
        ('5', 'Brno - Masarykova', 'Jižní Morava'),
        ('175', 'Kadaň', 'Severozápadní Čechy'),
        ('520', 'Újezd nad Lesy', 'Praha'),
        ('14', 'OC Olympia Brno', 'Jižní Morava'),
        ('516', 'OC Čakovice', 'Praha'),
        ('553', 'OC Olympia Plzeň', 'Jihozápadní Čechy'),
        ('488', 'Radotín', 'Praha'),
        ('416', 'Bruntál', 'Severní Morava'),
        ('595', 'Český Krumlov', 'Jihozápadní Čechy'),
        ('168', 'Rumburk', 'Severozápadní Čechy'),
        ('315', 'Vrchlabí', 'Východní Čechy'),
        ('265', 'Hořice', 'Východní Čechy'),
        ('292', 'Dobruška', 'Východní Čechy'),
        ('618', 'Prachatice', 'Jihozápadní Čechy'),
        ('472', 'GEMINI', 'Praha'),
        ('555', 'Nýřany', 'Jihozápadní Čechy'),
        ('449', 'Dlouhá', 'Praha'),
        ('212', 'Turnov', 'Severozápadní Čechy'),
        ('67', 'Vizovice', 'Jižní Morava'),
        ('36', 'Humpolec', 'Jižní Morava'),
        ('242', 'Lysá nad Labem', 'Východní Čechy'),
        ('402', 'Šternberk', 'Severní Morava'),
        ('325', 'Vysoké Mýto', 'Východní Čechy'),
        ('531', 'Horní Měcholupy', 'Praha'),
        ('53', 'Mikulov na Moravě', 'Jižní Morava'),
        ('353', 'Frenštát pod Radhoštěm', 'Severní Morava'),
        ('76', 'Veselí nad Moravou', 'Jižní Morava'),
        ('518', 'Vysočany', 'Praha'),
        ('188', 'OC Forum Liberec', 'Severozápadní Čechy'),
        ('637', 'Holýšov', 'Jihozápadní Čechy'),
        ('550', 'Blovice', 'Jihozápadní Čechy'),
        ('20', 'Tišnov', 'Jižní Morava'),
        ('157', 'Nové Strašecí', 'Severozápadní Čechy'),
        ('21', 'Židlochovice', 'Jižní Morava'),
        ('601', 'Dačice', 'Jihozápadní Čechy'),
        ('552', 'Přeštice', 'Jihozápadní Čechy'),
        ('666', 'Tachov', 'Jihozápadní Čechy'),
        ('159', 'Žatec', 'Severozápadní Čechy'),
        ('564', 'Votice', 'Jihozápadní Čechy'),
        ('602', 'Třeboň', 'Jihozápadní Čechy'),
        ('450', 'Na Příkopě', 'Praha'),
        ('454', 'Nuselská', 'Praha'),
        ('158', 'Podbořany', 'Severozápadní Čechy'),
        ('510', 'Řepy', 'Praha'),
        ('544', 'Plzeň - Slovany', 'Jihozápadní Čechy'),
        ('255', 'Hlinsko v Čechách', 'Východní Čechy'),
        ('149', 'Benátky nad Jizerou', 'Severozápadní Čechy'),
        ('45', 'Letovice', 'Jižní Morava'),
        ('301', 'Litomyšl', 'Východní Čechy'),
        ('332', 'Bystřice nad Pernštejnem', 'Východní Čechy'),
        ('95', 'Bystřice pod Hostýnem', 'Jižní Morava'),
        ('119', 'Moravský Krumlov', 'Jižní Morava'),
        ('303', 'Polička', 'Východní Čechy'),
        ('203', 'Litvínov', 'Severozápadní Čechy'),
        ('230', 'Český Brod', 'Východní Čechy'),
        ('193', 'Lovosice', 'Severozápadní Čechy'),
        ('492', 'Praha 5 - OC Zličín', 'Praha'),
        ('92', 'OC City Park Jihlava', 'Jižní Morava'),
        ('324', 'Lanškroun', 'Východní Čechy'),
        ('579', 'Trhové Sviny', 'Jihozápadní Čechy'),
        ('17', 'Ivančice', 'Jižní Morava'),
        ('339', 'Bílovec', 'Severní Morava'),
        ('222', 'Nový Bydžov', 'Východní Čechy'),
        ('545', 'Sušice', 'Jihozápadní Čechy'),
        ('44', 'Boskovice', 'Jižní Morava'),
        ('234', 'Pečky', 'Východní Čechy'),
        ('248', 'Ledeč nad Sázavou', 'Východní Čechy'),
        ('590', 'Č. Budějovice - OC Globus', 'Jihozápadní Čechy'),
        ('91', 'OC Třebíč', 'Jižní Morava'),
        ('672', 'Olomouc - OC Šantovka', 'Severní Morava'),
        ('86', 'Třešť', 'Jižní Morava'),
        ('120', 'Hrušovany nad Jevišovkou', 'Jižní Morava'),
        ('277', 'Jaroměř', 'Východní Čechy'),
        ('162', 'Nový Bor', 'Severozápadní Čechy'),
        ('184', 'Frýdlant v Čechách', 'Severozápadní Čechy'),
        ('294', 'Týniště nad Orlicí', 'Východní Čechy'),
        ('323', 'Česká Třebová', 'Východní Čechy'),
        ('286', 'Přelouč', 'Východní Čechy'),
        ('534', 'Kostelec nad Černými lesy', 'Východní Čechy'),
        ('554', 'Kralovice', 'Jihozápadní Čechy'),
        ('596', 'Kaplice', 'Jihozápadní Čechy'),
        ('24', 'Pohořelice', 'Jižní Morava'),
        ('293', 'Kostelec nad Orlicí', 'Východní Čechy'),
        ('328', 'Žamberk', 'Východní Čechy'),
        ('359', 'Ostrava - Poruba 8', 'Severní Morava'),
        ('334', 'Velká Bíteš', 'Východní Čechy'),
        ('274', 'Červený Kostelec', 'Východní Čechy'),
        ('187', 'Jablonec nad Nisou - OC Rýnovka', 'Severozápadní Čechy'),
        ('314', 'Dvůr Králové nad Labem', 'Východní Čechy'),
        ('247', 'Chotěboř', 'Východní Čechy'),
        ('581', 'Č. Budějovice - Sokolská', 'Jihozápadní Čechy'),
        ('94', 'Holešov', 'Jižní Morava'),
        ('89', 'Polná', 'Jižní Morava'),
        ('593', 'Č. Budějovice - Lidická', 'Jihozápadní Čechy'),
        ('398', 'OC HANÁ Olomouc', 'Severní Morava'),
        ('460', 'Karlovo nám.', 'Praha'),
        ('223', 'Futurum Hradec Králové', 'Východní Čechy'),
        ('215', 'Semily', 'Severozápadní Čechy'),
        ('12', 'Žabovřesky', 'Jižní Morava'),
        ('645', 'Mariánské Lázně', 'Jihozápadní Čechy'),
        ('264', 'Nová Paka', 'Východní Čechy'),
        ('169', 'Varnsdorf', 'Severozápadní Čechy'),
        ('491', 'Nové Butovice', 'Praha'),
        ('418', 'Vrbno pod Pradědem', 'Severní Morava'),
        ('613', 'Milevsko', 'Jihozápadní Čechy'),
        ('19', 'Rosice', 'Jižní Morava'),
        ('317', 'Úpice', 'Východní Čechy'),
        ('423', 'Kravaře', 'Severní Morava'),
        ('231', 'Čelákovice', 'Východní Čechy'),
        ('257', 'Skuteč', 'Východní Čechy'),
        ('662', 'Chodov', 'Jihozápadní Čechy'),
        ('576', 'Jílové u Prahy', 'Jihozápadní Čechy'),
        ('631', 'Sezimovo Ústí', 'Jihozápadní Čechy'),
        ('179', 'Tanvald', 'Severozápadní Čechy'),
        ('401', 'Olomouc - OC Bělidla', 'Severní Morava'),
        ('605', 'Suchdol nad Lužnicí', 'Jihozápadní Čechy'),
        ('572', 'Sedlčany', 'Jihozápadní Čechy'),
        ('500', 'KAMERA (Barrandov)', 'Praha'),
        ('327', 'Letohrad', 'Východní Čechy'),
        ('570', 'Sázava', 'Jihozápadní Čechy'),
        ('2', 'Brno - Česká', 'Jižní Morava'),
        ('651', 'Toužim', 'Jihozápadní Čechy'),
        ('117', 'Slavkov u Brna', 'Jižní Morava'),
        ('333', 'Nové Město na Moravě', 'Východní Čechy'),
        ('580', 'Týn nad Vltavou', 'Jihozápadní Čechy'),
        ('205', 'Bílina', 'Severozápadní Čechy'),
        ('283', 'Holice v Čechách', 'Východní Čechy'),
        ('395', 'Odry', 'Severní Morava'),
        ('619', 'Vimperk', 'Jihozápadní Čechy'),
        ('18', 'Kuřim', 'Jižní Morava'),
        ('464', 'Sladkovského nám.', 'Praha'),
        ('32', 'Šlapanice', 'Jižní Morava'),
        ('643', 'Aš', 'Jihozápadní Čechy'),
        ('186', 'Hrádek nad Nisou', 'Severozápadní Čechy'),
        ('573', 'Březnice', 'Jihozápadní Čechy'),
        ('221', 'Chlumec nad Cidlinou', 'Východní Čechy'),
        ('239', 'Zruč nad Sázavou', 'Východní Čechy'),
        ('102', 'Náměšť nad Oslavou', 'Jižní Morava'),
        ('161', 'Mimoň', 'Severozápadní Čechy'),
        ('125', 'Děčín 4', 'Severozápadní Čechy'),
        ('213', 'Jilemnice', 'Severozápadní Čechy'),
        ('417', 'Rýmařov', 'Severní Morava'),
        ('669', 'Planá', 'Jihozápadní Čechy'),
        ('194', 'Štětí', 'Severozápadní Čechy'),
        ('447', 'Vodičkova', 'Praha'),
        ('548', 'Horažďovice', 'Jihozápadní Čechy'),
        ('479', 'Palmovka', 'Praha'),
        ('399', 'Litovel', 'Severní Morava'),
        ('77', 'Strážnice', 'Jižní Morava'),
        ('273', 'Broumov', 'Východní Čechy'),
        ('254', 'Heřmanův Městec', 'Východní Čechy'),
        ('304', 'Jevíčko', 'Východní Čechy'),
        ('529', 'Uhříněves', 'Praha'),
        ('80', 'Bzenec', 'Jižní Morava'),
        ('302', 'Moravská Třebová', 'Východní Čechy'),
        ('330', 'Králíky', 'Východní Čechy'),
        ('237', 'Uhlířské Janovice', 'Východní Čechy'),
        ('626', 'Vodňany', 'Jihozápadní Čechy'),
        ('37', 'Pacov', 'Jižní Morava'),
        ('663', 'Kraslice', 'Jihozápadní Čechy'),
        ('495', 'Dělnická', 'Praha'),
        ('326', 'Choceň', 'Východní Čechy'),
        ('85', 'Telč', 'Jižní Morava'),
        ('115', 'Bučovice', 'Jižní Morava'),
        ('515', 'Praha 9 - OC Galerie Harfa', 'Praha'),
        ('648', 'Ostrov', 'Jihozápadní Čechy'),
        ('625', 'Blatná', 'Jihozápadní Čechy'),
        ('556', 'Plzeň - Skvrňany', 'Jihozápadní Čechy'),
        ('432', 'Lipník nad Bečvou', 'Severní Morava'),
        ('68', 'Zlín - Dvanáctka', 'Jižní Morava'),
        ('220', 'Hradec Králové - OC Aupark', 'Východní Čechy'),
        ('173', 'Česká Kamenice', 'Severozápadní Čechy'),
    ]
    cur.executemany("""
        INSERT INTO pobocky (id_pobocky, nazev, region)
        VALUES (?, ?, ?)
    """, pobocky_data)

    conn.commit()
    conn.close()
    print(f"Vytvořena vzorová databáze: {db_path}")


if __name__ == "__main__":
    main()
